### ISSUE TITLE
Standardize scraping for American Job Center sites such as DE and KS

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#126]
Create a single library capable of scraping WARN notices hosted on American Job Center sites.

Below is a running list of states that use the sites, with links and related issues:

## Tasks

- [x] Create JobCenterSite platform class and related helpers to enable date-based scraping
- [x]  Add detail record page fields to `exports/ks.csv`
- [x] Apply new strategy to state modules
  - [x] [AZ][]
    - #177
  - [x] [DE][]
    - #122
    - #123
  - [x] [KS][]
    - #127
  - [x] [OK][]
    - #138
- [x] Perform data quality checks for all states
- [x] Create docs pages for JobCenter sites with references from state-level docs pages. State pages should include any details specific to that state about scraping strategy.
- [x] Create issue mentioning need for data quality script(s) that address missing Notice Dates and new historical years (with a reference to the description in the Job Center docs)

## Implementation

Scrapes of Job Center sites could be easily optimized to only check for some time period (day, week, month, year) using the basic search form:

https://www.kansasworks.com/search/warn_lookups/new

We can code the scrapers to backfill using a yearly search, for example. We can scrape current year and go backwards until there are no more records. Or if we know the start year for a give place, we can start at that known year and scraper going forward until we get current, caching pages along the way.

Alternatively, we could use the current strategy (see URL below) and sort the full results by year in reverse chron. Then, we can work backwards through the paged results until a prior year is encountered. The relevant URL query param is `q[s]=notice_on+desc` in the below sample URL for Delaware:

> https://joblink.delaware.gov/search/warn_lookups?commit=Search&page=1&q%5Bemployer_name_cont%5D=&q%5Bmain_contact_contact_info_addresses_full_location_city_matches%5D=&q%5Bnotice_eq%5D=&q%5Bnotice_on_gteq%5D=&q%5Bnotice_on_lteq%5D=&q%5Bs%5D=notice_on+desc&q%5Bservice_delivery_area_id_eq%5D=&q%5Bzipcode_code_start%5D=&utf8=%E2%9C%93

[AZ]: https://www.azjobconnection.gov/search/warn_lookups?commit=Search&page=2&q%5Bemployer_name_cont%5D=&q%5Bmain_contact_contact_info_addresses_full_location_city_matches%5D=&q%5Bnotice_eq%5D=&q%5Bnotice_on_gteq%5D=&q%5Bnotice_on_lteq%5D=&q%5Bs%5D=notice_on+asc&q%5Bservice_delivery_area_id_eq%5D=&q%5Bzipcode_code_start%5D=&utf8=%E2%9C%93

[DE]: https://joblink.delaware.gov/search/warn_lookups?commit=Search&page=1&q%5Bemployer_name_cont%5D=&q%5Bmain_contact_contact_info_addresses_full_location_city_matches%5D=&q%5Bnotice_eq%5D=&q%5Bnotice_on_gteq%5D=&q%5Bnotice_on_lteq%5D=&q%5Bs%5D=notice_on+desc&q%5Bservice_delivery_area_id_eq%5D=&q%5Bzipcode_code_start%5D=&utf8=%E2%9C%93

[KS]: https://www.kansasworks.com/search/warn_lookups?commit=Search&page=1&q%5Bemployer_name_cont%5D=&q%5Bmain_contact_contact_info_addresses_full_location_city_matches%5D=&q%5Bnotice_eq%5D=true&q%5Bnotice_on_gteq%5D=&q%5Bnotice_on_lteq%5D=&q%5Bs%5D=notice_on+desc&q%5Bservice_delivery_area_id_eq%5D=&q%5Bzipcode_code_start%5D=&utf8=%E2%9C%93 

[OK]: https://okjobmatch.com/search/warn_lookups?commit=Search&page=1&q%5Bemployer_name_cont%5D=&q%5Bmain_contact_contact_info_addresses_full_location_city_matches%5D=&q%5Bnotice_eq%5D=&q%5Bs%5D=notice_on+desc&q%5Bservice_delivery_area_id_eq%5D=&q%5Bzipcode_code_start%5D=&utf8=%E2%9C%93
