### ISSUE TITLE
Finalize and document strategy for non-standard states

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#242]
We should document the current status of recently merged code for places such as NY and OR (and possibly others?) that rely on non-standard data acquisition strategies (e.g. the use of static historical files and/or records requests filed on a regular schedule). We'll need to document these edge cases in multiple places, such as:

- state-specific pages in the `docs/` dir
- main README.md where we prominently mention edge-case states and link out to them
- BLN project description and README 

We should also discuss overall strategy for ensuring we stay on top of updates for non-standard states, in particular those that require public records requests. For example, we should set up an automated system (e.g. through MuckRock) or at least calendar reminders for any states that require public records requests. 

Step 1 will be compiling a list of these edge-case states. Then we can decide on best strategies to handle. 

## Tasks

- [x] Create `docs/ca.md`
- [ ] Update `docs/ny.md`
- [ ] Update `docs/tx.md`

**Comment by ydoc5212** [comment]
Current list of states that rely on historical documents:
- TX (downloads historical and merges with web srcaping)
- OR (just downloads historical but can re-enable web scraping, too)
- NY (just downloads historical)
- CA (dont know a lot about CA's strategy)

**Comment by zstumgoren** [comment]
@ydoc5212 Thanks. Note that CA is no longer an edge-case state (I updated to handle both historical PDFs and Excel file for current fiscal year). I can create docs for CA (should've done that to begin with). Would you mind updating the docs pages for TX and NY to briefly describe the way our process and/or code currently works? I.e., if they require regular requests for data files, we should note that prominently at top. 

Let's leave OR docs as is for now until we can chat about strategy going forward.

**Comment by ydoc5212** [comment]
can do!

**Comment by zstumgoren** [comment]
@ydoc5212 Thanks! Heads up that I just added `docs/ca.md` so you should pull on `main` branch before starting updates

**Comment by palewire** [comment]
Here's a proposal: We develop a simple metadata structure to be embedded at the top of each scrape .py file. It would include some kind of classification of what "type" of scraper it is, which could then be automatically collected by my documentation writer and spit into the table on our site. Then nobody has to tend a spreadsheet, and the decisions we make stay close to the code.

I'm imagining something like:

__scrapertype__ = "platform"

or

__scrapertype__ = "historical"

or whatever.

**Comment by zstumgoren** [comment]
+1 to a classification system combined with auto-gen'd docs. Other than the 7 or so JobCenter states, I haven't noticed other platform sites for WARN yet. But it's quite possible there are more. And I imagine there are other metadata tidbits worth tracking that don't immediately come to mind, so having a system like this in place would set us up nicely to expand going forward

**Comment by palewire** [comment]
Historial scrapers are now tagged in our docs dashboard https://warn-scraper.readthedocs.io/en/latest/sources.html

**Comment by chriszs** [comment]
Filed a FOIL with New York I pre-negotiated with their WARN coordinator for an expanded timeframe, but just had to jog them prior to their statutory deadline. I wonder if standardizing on Muckrock to record exchanges in an open way, some sort of scheduled reminder makes sense.
